title: re1gn
email: ""
description: >-
  Personal site for project writeups, rants, and builds.
baseurl: ""
url: "https://re1gn182.github.io"
markdown: kramdown
theme: null
plugins: []
permalink: /:categories/:year/:month/:day/:title/

collections:
  pages:
    output: true
